### ISSUE TITLE
Dashboard component does not display

### ISSUE THREAD

**Issue by BearAlliance** [gd46/angular-webpack#3]
Looks like the root `app-component` is fine, but the `/dashboard` route is not rendered, either by clicking the link, or URL navigation

![screen shot 2018-01-23 at 9 26 20 am](https://user-images.githubusercontent.com/8557692/35280936-ac03e534-001f-11e8-8571-9a3d2a571f85.png)

**Comment by BearAlliance** [comment]
it seems like the default route is the dashboard component
`dashboard.module.ts`
```
 RouterModule.forChild([
      {
        path: '',
        component: DashboardComponent
      }
    ])
```

which contrasts with the router link
`app.html`
```
<nav>
  <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
</nav>
```
there is no `/dashboard` route registered

**Comment by gd46** [comment]
I pushed a fix, had a typo in the lazy load string. 

So app lazy loads the DashboardModule on the route /dashboard

The DashboardModule has the path empty string defined which loads the Dashboard component on the route of /dashboard.

**Comment by BearAlliance** [comment]
Nice, that did it. Didn't notice that it was a child route
